### ISSUE TITLE
Release 0.2.0 seems broken

### ISSUE THREAD

**Issue by jharbott** [jtimberman/chef-handler-updated-resources#2]
Getting

```
[2015-06-26T07:33:35+00:00] INFO: Resources updated this run:
[2015-06-26T07:33:35+00:00] ERROR: Report handler SimpleReport::UpdatedResources raised #<NameError: undefined local variable or method `line_prefix' for #<SimpleReport::UpdatedResources:0x000000060feac8>>
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-updated-resources-0.2.0/lib/chef/handler/updated_resources.rb:28:in `block in report'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-updated-resources-0.2.0/lib/chef/handler/updated_resources.rb:28:in `each'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-updated-resources-0.2.0/lib/chef/handler/updated_resources.rb:28:in `report'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:214:in `run_report_safely'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:93:in `block in run_report_handlers'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:92:in `each'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:92:in `run_report_handlers'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:103:in `block in <class:Handler>'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:125:in `call'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:125:in `block in run_completed_successfully'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:124:in `each'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:124:in `run_completed_successfully'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:437:in `do_run'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:213:in `block in run'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:207:in `fork'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:207:in `run'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application.rb:236:in `run_chef_client'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application/client.rb:338:in `block in run_application'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application/client.rb:327:in `loop'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application/client.rb:327:in `run_application'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application.rb:55:in `run'
[2015-06-26T07:33:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/bin/chef-client:26:in `<top (required)>'
[2015-06-26T07:33:35+00:00] ERROR: /usr/bin/chef-client:23:in `load'
[2015-06-26T07:33:35+00:00] ERROR: /usr/bin/chef-client:23:in `<main>'
  - SimpleReport::UpdatedResources
```

**Comment by jharbott** [comment]
There is also a second bug which isn't fixed by @jklare's patch, this error when there are no updated resources, e.g. because the chef-run fails during compilation already:

```
[2015-07-23T08:05:19+00:00] INFO: Resources updated this run:
[2015-07-23T08:05:19+00:00] ERROR: Report handler SimpleReport::UpdatedResources raised #<NoMethodError: undefined method `each' for nil:NilClass>
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-handler-updated-resources-0.2.0/lib/chef/handler/updated_resources.rb:28:in `report'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `each'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:428:in `call'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:428:in `block in run_failed'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:427:in `each'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:427:in `run_failed'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:296:in `rescue in run'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:306:in `run'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
[2015-07-23T08:05:19+00:00] ERROR: /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-07-23T08:05:19+00:00] ERROR: /usr/bin/chef-client:55:in `load'
[2015-07-23T08:05:19+00:00] ERROR: /usr/bin/chef-client:55:in `<main>'
    - SimpleReport::UpdatedResources
```

**Comment by jklare** [comment]
issue should be fixed with recently merged patch, but still needs a new gem release

**Comment by jtimberman** [comment]
v0.3.0 was released which should contain the fix for this.
